import Footer from "./component/footer/Footer";
import Header from "./component/header/Header";
import Modal from "./component/modal/Modal";
import ModalChild from "./component/modal/ModalChild";
import "./globals.css";
import { CalcValProvider } from "./provider/CalcValProvider";
import ModalChildProvider from "./provider/ModalChildProvider";
import ModalProvider from "./provider/ModalProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body >
        <CalcValProvider>
          <ModalProvider>
            <ModalChildProvider>
              <div className="flex flex-col gap-5 w-full min-h-screen">
                <Header />
                <main className="flex grow w-full">
                  <div className="container mx-auto">
                    {children}
                  </div>
                </main>
                <ModalChild />
                <Modal />
                <Footer />
              </div>
            </ModalChildProvider>
          </ModalProvider>
        </CalcValProvider>
      </body>
    </html>
  );
}
